# Generated by Django 4.2.23 on 2025-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="id",
        ),
        migrations.AddField(
            model_name="clusterresult",
            name="messages",
            field=models.ManyToManyField(
                blank=True, related_name="cluster_results", to="faq_api.message"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="author_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="channel",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="direction",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="gpt_label",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="sentiment",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
